steps:
  # Build the Docker image with build-time environment variables
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_GA_MEASUREMENT_ID=${_GA_MEASUREMENT_ID}'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/container/repave-website:${COMMIT_SHA}'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/container/repave-website:latest'
      - '.'

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '--all-tags'
      - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/container/repave-website'
    waitFor: ['build-image']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-to-cloud-run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'repave-website'
      - '--image'
      - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/container/repave-website:${COMMIT_SHA}'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production'
    waitFor: ['push-image']

# Store images in Artifact Registry
images:
  - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/container/repave-website:${COMMIT_SHA}'
  - 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/container/repave-website:latest'

# Substitutions (default values)
substitutions:
  _GA_MEASUREMENT_ID: 'G-2FXGM4JHE4'

# Options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout
timeout: '1200s'
